services:
  - type: web
    name: nocap
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: free
    healthCheckPath: /docs

    envVars:

      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        value: sqlite:///store.db
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET 
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "llama-3.3-70b-versatile"
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: OWNER_EMAIL
        sync: false
